2018-10-28 21:30:09,796 ERROR: Exception on /index [GET] [in g:\programs\termassignment\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "g:\programs\termassignment\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "g:\programs\termassignment\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "g:\programs\termassignment\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "g:\programs\termassignment\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "g:\programs\termassignment\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "g:\programs\termassignment\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "G:\programs\TermAssignment\app\url_mapping.py", line 15, in index
    return render_template('index.html', title='HomePage')
  File "g:\programs\termassignment\venv\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "g:\programs\termassignment\venv\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "g:\programs\termassignment\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "g:\programs\termassignment\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "G:\programs\TermAssignment\app\templates\index.html", line 18, in top-level template code
    <li><a href="{{ url_for('userprofile?username=user') }}">Profile</a></li>
  File "g:\programs\termassignment\venv\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "g:\programs\termassignment\venv\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "g:\programs\termassignment\venv\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "g:\programs\termassignment\venv\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
BuildError: Could not build url for endpoint 'userprofile'. Did you forget to specify values ['username']?
2018-10-28 21:30:10,697 ERROR: Exception on /index [GET] [in g:\programs\termassignment\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "g:\programs\termassignment\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "g:\programs\termassignment\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "g:\programs\termassignment\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "g:\programs\termassignment\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "g:\programs\termassignment\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "g:\programs\termassignment\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "G:\programs\TermAssignment\app\url_mapping.py", line 15, in index
    return render_template('index.html', title='HomePage')
  File "g:\programs\termassignment\venv\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "g:\programs\termassignment\venv\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "g:\programs\termassignment\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "g:\programs\termassignment\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "G:\programs\TermAssignment\app\templates\index.html", line 18, in top-level template code
    <li><a href="{{ url_for('userprofile?username=user') }}">Profile</a></li>
  File "g:\programs\termassignment\venv\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "g:\programs\termassignment\venv\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "g:\programs\termassignment\venv\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "g:\programs\termassignment\venv\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
BuildError: Could not build url for endpoint 'userprofile'. Did you forget to specify values ['username']?
2018-10-28 21:30:23,384 ERROR: Exception on /index [GET] [in g:\programs\termassignment\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "g:\programs\termassignment\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "g:\programs\termassignment\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "g:\programs\termassignment\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "g:\programs\termassignment\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "g:\programs\termassignment\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "g:\programs\termassignment\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "G:\programs\TermAssignment\app\url_mapping.py", line 15, in index
    return render_template('index.html', title='HomePage')
  File "g:\programs\termassignment\venv\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "g:\programs\termassignment\venv\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "g:\programs\termassignment\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "g:\programs\termassignment\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "G:\programs\TermAssignment\app\templates\index.html", line 18, in top-level template code
    <!-- <li><a href="{{ url_for('userprofile?username=user') }}">Profile</a></li>         -->
  File "g:\programs\termassignment\venv\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "g:\programs\termassignment\venv\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "g:\programs\termassignment\venv\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "g:\programs\termassignment\venv\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
BuildError: Could not build url for endpoint 'userprofile'. Did you forget to specify values ['username']?
